# coding=utf-8

from django.utils.translation import ugettext_lazy as _


countries = {
    '001': _(u'World'),
    '002': _(u'Africa'),
    '003': _(u'North America'),
    '005': _(u'South America'),
    '009': _(u'Oceania'),
    '011': _(u'Western Africa'),
    '013': _(u'Central America'),
    '014': _(u'Eastern Africa'),
    '015': _(u'Northern Africa'),
    '017': _(u'Middle Africa'),
    '018': _(u'Southern Africa'),
    '019': _(u'Americas'),
    '021': _(u'Northern America'),
    '029': _(u'Caribbean'),
    '030': _(u'Eastern Asia'),
    '034': _(u'Southern Asia'),
    '035': _(u'South-Eastern Asia'),
    '039': _(u'Southern Europe'),
    '053': _(u'Australia and New Zealand'),
    '054': _(u'Melanesia'),
    '057': _(u'Micronesian Region'),
    '061': _(u'Polynesia'),
    '062': _(u'South-Central Asia'),
    '142': _(u'Asia'),
    '143': _(u'Central Asia'),
    '145': _(u'Western Asia'),
    '150': _(u'Europe'),
    '151': _(u'Eastern Europe'),
    '154': _(u'Northern Europe'),
    '155': _(u'Western Europe'),
    '172': _(u'Commonwealth of Independent States'),
    '200': _(u'Czechoslovakia'),
    '419': _(u'Latin America and the Caribbean'),
    '830': _(u'Channel Islands'),
    'AC': _(u'Ascension Island'),
    'AD': _(u'Andorra'),
    'AE': _(u'United Arab Emirates'),
    'AF': _(u'Afghanistan'),
    'AG': _(u'Antigua and Barbuda'),
    'AI': _(u'Anguilla'),
    'AL': _(u'Albania'),
    'AM': _(u'Armenia'),
    'AN': _(u'Netherlands Antilles'),
    'AO': _(u'Angola'),
    'AQ': _(u'Antarctica'),
    'AR': _(u'Argentina'),
    'AS': _(u'American Samoa'),
    'AT': _(u'Austria'),
    'AU': _(u'Australia'),
    'AW': _(u'Aruba'),
    'AX': _(u'Åland Islands'),
    'AZ': _(u'Azerbaijan'),
    'BA': _(u'Bosnia and Herzegovina'),
    'BB': _(u'Barbados'),
    'BD': _(u'Bangladesh'),
    'BE': _(u'Belgium'),
    'BF': _(u'Burkina Faso'),
    'BG': _(u'Bulgaria'),
    'BH': _(u'Bahrain'),
    'BI': _(u'Burundi'),
    'BJ': _(u'Benin'),
    'BL': _(u'Saint Barthélemy'),
    'BM': _(u'Bermuda'),
    'BN': _(u'Brunei'),
    'BO': _(u'Bolivia'),
    'BQ': _(u'British Antarctic Territory'),
    'BR': _(u'Brazil'),
    'BS': _(u'Bahamas'),
    'BT': _(u'Bhutan'),
    'BV': _(u'Bouvet Island'),
    'BW': _(u'Botswana'),
    'BY': _(u'Belarus'),
    'BZ': _(u'Belize'),
    'CA': _(u'Canada'),
    'CC': _(u'Cocos [Keeling] Islands'),
    'CD': _(u'Congo - Kinshasa'),
    'CD': _(u'Congo [DRC]'),
    'CF': _(u'Central African Republic'),
    'CG': _(u'Congo - Brazzaville'),
    'CG': _(u'Congo [Republic]'),
    'CH': _(u'Switzerland'),
    'CI': _(u'Côte d’Ivoire'),
    'CI': _(u'Ivory Coast'),
    'CK': _(u'Cook Islands'),
    'CL': _(u'Chile'),
    'CM': _(u'Cameroon'),
    'CN': _(u'China'),
    'CO': _(u'Colombia'),
    'CP': _(u'Clipperton Island'),
    'CR': _(u'Costa Rica'),
    'CS': _(u'Serbia and Montenegro'),
    'CT': _(u'Canton and Enderbury Islands'),
    'CU': _(u'Cuba'),
    'CV': _(u'Cape Verde'),
    'CX': _(u'Christmas Island'),
    'CY': _(u'Cyprus'),
    'CZ': _(u'Czech Republic'),
    'DD': _(u'East Germany'),
    'DE': _(u'Germany'),
    'DG': _(u'Diego Garcia'),
    'DJ': _(u'Djibouti'),
    'DK': _(u'Denmark'),
    'DM': _(u'Dominica'),
    'DO': _(u'Dominican Republic'),
    'DZ': _(u'Algeria'),
    'EA': _(u'Ceuta and Melilla'),
    'EC': _(u'Ecuador'),
    'EE': _(u'Estonia'),
    'EG': _(u'Egypt'),
    'EH': _(u'Western Sahara'),
    'ER': _(u'Eritrea'),
    'ES': _(u'Spain'),
    'ET': _(u'Ethiopia'),
    'EU': _(u'European Union'),
    'FI': _(u'Finland'),
    'FJ': _(u'Fiji'),
    'FK': _(u'Falkland Islands'),
    'FK': _(u'Falkland Islands [Islas Malvinas]'),
    'FM': _(u'Micronesia'),
    'FO': _(u'Faroe Islands'),
    'FQ': _(u'French Southern and Antarctic Territories'),
    'FR': _(u'France'),
    'FX': _(u'Metropolitan France'),
    'GA': _(u'Gabon'),
    'GB': _(u'United Kingdom'),
    'GD': _(u'Grenada'),
    'GE': _(u'Georgia'),
    'GF': _(u'French Guiana'),
    'GG': _(u'Guernsey'),
    'GH': _(u'Ghana'),
    'GI': _(u'Gibraltar'),
    'GL': _(u'Greenland'),
    'GM': _(u'Gambia'),
    'GN': _(u'Guinea'),
    'GP': _(u'Guadeloupe'),
    'GQ': _(u'Equatorial Guinea'),
    'GR': _(u'Greece'),
    'GS': _(u'South Georgia and the South Sandwich Islands'),
    'GT': _(u'Guatemala'),
    'GU': _(u'Guam'),
    'GW': _(u'Guinea-Bissau'),
    'GY': _(u'Guyana'),
    'HK': _(u'Hong Kong SAR China'),
    'HK': _(u'Hong Kong'),
    'HM': _(u'Heard Island and McDonald Islands'),
    'HN': _(u'Honduras'),
    'HR': _(u'Croatia'),
    'HT': _(u'Haiti'),
    'HU': _(u'Hungary'),
    'IC': _(u'Canary Islands'),
    'ID': _(u'Indonesia'),
    'IE': _(u'Ireland'),
    'IL': _(u'Israel'),
    'IM': _(u'Isle of Man'),
    'IN': _(u'India'),
    'IO': _(u'British Indian Ocean Territory'),
    'IQ': _(u'Iraq'),
    'IR': _(u'Iran'),
    'IS': _(u'Iceland'),
    'IT': _(u'Italy'),
    'JE': _(u'Jersey'),
    'JM': _(u'Jamaica'),
    'JO': _(u'Jordan'),
    'JP': _(u'Japan'),
    'JT': _(u'Johnston Island'),
    'KE': _(u'Kenya'),
    'KG': _(u'Kyrgyzstan'),
    'KH': _(u'Cambodia'),
    'KI': _(u'Kiribati'),
    'KM': _(u'Comoros'),
    'KN': _(u'Saint Kitts and Nevis'),
    'KP': _(u'North Korea'),
    'KR': _(u'South Korea'),
    'KW': _(u'Kuwait'),
    'KY': _(u'Cayman Islands'),
    'KZ': _(u'Kazakhstan'),
    'LA': _(u'Laos'),
    'LB': _(u'Lebanon'),
    'LC': _(u'Saint Lucia'),
    'LI': _(u'Liechtenstein'),
    'LK': _(u'Sri Lanka'),
    'LR': _(u'Liberia'),
    'LS': _(u'Lesotho'),
    'LT': _(u'Lithuania'),
    'LU': _(u'Luxembourg'),
    'LV': _(u'Latvia'),
    'LY': _(u'Libya'),
    'MA': _(u'Morocco'),
    'MC': _(u'Monaco'),
    'MD': _(u'Moldova'),
    'ME': _(u'Montenegro'),
    'MF': _(u'Saint Martin'),
    'MG': _(u'Madagascar'),
    'MH': _(u'Marshall Islands'),
    'MI': _(u'Midway Islands'),
    'MK': _(u'Macedonia'),
    'MK': _(u'Macedonia [FYROM]'),
    'ML': _(u'Mali'),
    'MM': _(u'Myanmar [Burma]'),
    'MN': _(u'Mongolia'),
    'MO': _(u'Macau SAR China'),
    'MO': _(u'Macau'),
    'MP': _(u'Northern Mariana Islands'),
    'MQ': _(u'Martinique'),
    'MR': _(u'Mauritania'),
    'MS': _(u'Montserrat'),
    'MT': _(u'Malta'),
    'MU': _(u'Mauritius'),
    'MV': _(u'Maldives'),
    'MW': _(u'Malawi'),
    'MX': _(u'Mexico'),
    'MY': _(u'Malaysia'),
    'MZ': _(u'Mozambique'),
    'NA': _(u'Namibia'),
    'NC': _(u'New Caledonia'),
    'NE': _(u'Niger'),
    'NF': _(u'Norfolk Island'),
    'NG': _(u'Nigeria'),
    'NI': _(u'Nicaragua'),
    'NL': _(u'Netherlands'),
    'NO': _(u'Norway'),
    'NP': _(u'Nepal'),
    'NQ': _(u'Dronning Maud Land'),
    'NR': _(u'Nauru'),
    'NT': _(u'Neutral Zone'),
    'NU': _(u'Niue'),
    'NZ': _(u'New Zealand'),
    'OM': _(u'Oman'),
    'PA': _(u'Panama'),
    'PC': _(u'Pacific Islands Trust Territory'),
    'PE': _(u'Peru'),
    'PF': _(u'French Polynesia'),
    'PG': _(u'Papua New Guinea'),
    'PH': _(u'Philippines'),
    'PK': _(u'Pakistan'),
    'PL': _(u'Poland'),
    'PM': _(u'Saint Pierre and Miquelon'),
    'PN': _(u'Pitcairn Islands'),
    'PR': _(u'Puerto Rico'),
    'PS': _(u'Palestinian Territories'),
    'PT': _(u'Portugal'),
    'PU': _(u'U.S. Miscellaneous Pacific Islands'),
    'PW': _(u'Palau'),
    'PY': _(u'Paraguay'),
    'PZ': _(u'Panama Canal Zone'),
    'QA': _(u'Qatar'),
    'QO': _(u'Outlying Oceania'),
    'RE': _(u'Réunion'),
    'RO': _(u'Romania'),
    'RS': _(u'Serbia'),
    'RU': _(u'Russia'),
    'RW': _(u'Rwanda'),
    'SA': _(u'Saudi Arabia'),
    'SB': _(u'Solomon Islands'),
    'SC': _(u'Seychelles'),
    'SD': _(u'Sudan'),
    'SE': _(u'Sweden'),
    'SG': _(u'Singapore'),
    'SH': _(u'Saint Helena'),
    'SI': _(u'Slovenia'),
    'SJ': _(u'Svalbard and Jan Mayen'),
    'SK': _(u'Slovakia'),
    'SL': _(u'Sierra Leone'),
    'SM': _(u'San Marino'),
    'SN': _(u'Senegal'),
    'SO': _(u'Somalia'),
    'SR': _(u'Suriname'),
    'ST': _(u'São Tomé and Príncipe'),
    'SU': _(u'Union of Soviet Socialist Republics'),
    'SV': _(u'El Salvador'),
    'SY': _(u'Syria'),
    'SZ': _(u'Swaziland'),
    'TA': _(u'Tristan da Cunha'),
    'TC': _(u'Turks and Caicos Islands'),
    'TD': _(u'Chad'),
    'TF': _(u'French Southern Territories'),
    'TG': _(u'Togo'),
    'TH': _(u'Thailand'),
    'TJ': _(u'Tajikistan'),
    'TK': _(u'Tokelau'),
    'TL': _(u'Timor-Leste'),
    'TL': _(u'East Timor'),
    'TM': _(u'Turkmenistan'),
    'TN': _(u'Tunisia'),
    'TO': _(u'Tonga'),
    'TR': _(u'Turkey'),
    'TT': _(u'Trinidad and Tobago'),
    'TV': _(u'Tuvalu'),
    'TW': _(u'Taiwan'),
    'TZ': _(u'Tanzania'),
    'UA': _(u'Ukraine'),
    'UG': _(u'Uganda'),
    'UM': _(u'U.S. Minor Outlying Islands'),
    'US': _(u'United States'),
    'UY': _(u'Uruguay'),
    'UZ': _(u'Uzbekistan'),
    'VA': _(u'Vatican City'),
    'VC': _(u'Saint Vincent and the Grenadines'),
    'VD': _(u'North Vietnam'),
    'VE': _(u'Venezuela'),
    'VG': _(u'British Virgin Islands'),
    'VI': _(u'U.S. Virgin Islands'),
    'VN': _(u'Vietnam'),
    'VU': _(u'Vanuatu'),
    'WF': _(u'Wallis and Futuna'),
    'WK': _(u'Wake Island'),
    'WS': _(u'Samoa'),
    'YD': _(u'People\'s Democratic Republic of Yemen'),
    'YE': _(u'Yemen'),
    'YT': _(u'Mayotte'),
    'ZA': _(u'South Africa'),
    'ZM': _(u'Zambia'),
    'ZW': _(u'Zimbabwe'),
    'ZZ': _(u'Unknown or Invalid Region'),
}
