# coding=utf-8

from django.utils.translation import gettext_lazy as _


countries = {
    '001': _('world'),
    '002': _('Africa'),
    '003': _('North America'),
    '005': _('South America'),
    '009': _('Oceania'),
    '011': _('Western Africa'),
    '013': _('Central America'),
    '014': _('Eastern Africa'),
    '015': _('Northern Africa'),
    '017': _('Middle Africa'),
    '018': _('Southern Africa'),
    '019': _('Americas'),
    '021': _('Northern America'),
    '029': _('Caribbean'),
    '030': _('Eastern Asia'),
    '034': _('Southern Asia'),
    '035': _('Southeast Asia'),
    '039': _('Southern Europe'),
    '053': _('Australasia'),
    '054': _('Melanesia'),
    '057': _('Micronesian Region'),
    '061': _('Polynesia'),
    '142': _('Asia'),
    '143': _('Central Asia'),
    '145': _('Western Asia'),
    '150': _('Europe'),
    '151': _('Eastern Europe'),
    '154': _('Northern Europe'),
    '155': _('Western Europe'),
    '202': _('Sub-Saharan Africa'),
    '419': _('Latin America'),
    'AC': _('Ascension Island'),
    'AD': _('Andorra'),
    'AE': _('United Arab Emirates'),
    'AF': _('Afghanistan'),
    'AG': _('Antigua & Barbuda'),
    'AI': _('Anguilla'),
    'AL': _('Albania'),
    'AM': _('Armenia'),
    'AO': _('Angola'),
    'AQ': _('Antarctica'),
    'AR': _('Argentina'),
    'AS': _('American Samoa'),
    'AT': _('Austria'),
    'AU': _('Australia'),
    'AW': _('Aruba'),
    'AX': _('Åland Islands'),
    'AZ': _('Azerbaijan'),
    'BA': _('Bosnia & Herzegovina'),
    'BA': _('Bosnia'),
    'BB': _('Barbados'),
    'BD': _('Bangladesh'),
    'BE': _('Belgium'),
    'BF': _('Burkina Faso'),
    'BG': _('Bulgaria'),
    'BH': _('Bahrain'),
    'BI': _('Burundi'),
    'BJ': _('Benin'),
    'BL': _('St. Barthélemy'),
    'BM': _('Bermuda'),
    'BN': _('Brunei'),
    'BO': _('Bolivia'),
    'BQ': _('Caribbean Netherlands'),
    'BR': _('Brazil'),
    'BS': _('Bahamas'),
    'BT': _('Bhutan'),
    'BV': _('Bouvet Island'),
    'BW': _('Botswana'),
    'BY': _('Belarus'),
    'BZ': _('Belize'),
    'CA': _('Canada'),
    'CC': _('Cocos (Keeling) Islands'),
    'CD': _('Congo - Kinshasa'),
    'CD': _('Congo (DRC)'),
    'CF': _('Central African Republic'),
    'CG': _('Congo - Brazzaville'),
    'CG': _('Congo (Republic)'),
    'CH': _('Switzerland'),
    'CI': _('Côte d’Ivoire'),
    'CI': _('Ivory Coast'),
    'CK': _('Cook Islands'),
    'CL': _('Chile'),
    'CM': _('Cameroon'),
    'CN': _('China'),
    'CO': _('Colombia'),
    'CP': _('Clipperton Island'),
    'CQ': _('Sark'),
    'CR': _('Costa Rica'),
    'CU': _('Cuba'),
    'CV': _('Cape Verde'),
    'CV': _('Cabo Verde'),
    'CW': _('Curaçao'),
    'CX': _('Christmas Island'),
    'CY': _('Cyprus'),
    'CZ': _('Czechia'),
    'CZ': _('Czech Republic'),
    'DE': _('Germany'),
    'DG': _('Diego Garcia'),
    'DJ': _('Djibouti'),
    'DK': _('Denmark'),
    'DM': _('Dominica'),
    'DO': _('Dominican Republic'),
    'DZ': _('Algeria'),
    'EA': _('Ceuta & Melilla'),
    'EC': _('Ecuador'),
    'EE': _('Estonia'),
    'EG': _('Egypt'),
    'EH': _('Western Sahara'),
    'ER': _('Eritrea'),
    'ES': _('Spain'),
    'ET': _('Ethiopia'),
    'EU': _('European Union'),
    'EZ': _('Eurozone'),
    'FI': _('Finland'),
    'FJ': _('Fiji'),
    'FK': _('Falkland Islands'),
    'FK': _('Falkland Islands (Islas Malvinas)'),
    'FM': _('Micronesia'),
    'FO': _('Faroe Islands'),
    'FR': _('France'),
    'GA': _('Gabon'),
    'GB': _('United Kingdom'),
    'GB': _('UK'),
    'GD': _('Grenada'),
    'GE': _('Georgia'),
    'GF': _('French Guiana'),
    'GG': _('Guernsey'),
    'GH': _('Ghana'),
    'GI': _('Gibraltar'),
    'GL': _('Greenland'),
    'GM': _('Gambia'),
    'GN': _('Guinea'),
    'GP': _('Guadeloupe'),
    'GQ': _('Equatorial Guinea'),
    'GR': _('Greece'),
    'GS': _('South Georgia & South Sandwich Islands'),
    'GT': _('Guatemala'),
    'GU': _('Guam'),
    'GW': _('Guinea-Bissau'),
    'GY': _('Guyana'),
    'HK': _('Hong Kong SAR China'),
    'HK': _('Hong Kong'),
    'HM': _('Heard & McDonald Islands'),
    'HN': _('Honduras'),
    'HR': _('Croatia'),
    'HT': _('Haiti'),
    'HU': _('Hungary'),
    'IC': _('Canary Islands'),
    'ID': _('Indonesia'),
    'IE': _('Ireland'),
    'IL': _('Israel'),
    'IM': _('Isle of Man'),
    'IN': _('India'),
    'IO': _('British Indian Ocean Territory'),
    'IO': _('Chagos Archipelago'),
    'IQ': _('Iraq'),
    'IR': _('Iran'),
    'IS': _('Iceland'),
    'IT': _('Italy'),
    'JE': _('Jersey'),
    'JM': _('Jamaica'),
    'JO': _('Jordan'),
    'JP': _('Japan'),
    'KE': _('Kenya'),
    'KG': _('Kyrgyzstan'),
    'KH': _('Cambodia'),
    'KI': _('Kiribati'),
    'KM': _('Comoros'),
    'KN': _('St. Kitts & Nevis'),
    'KP': _('North Korea'),
    'KR': _('South Korea'),
    'KW': _('Kuwait'),
    'KY': _('Cayman Islands'),
    'KZ': _('Kazakhstan'),
    'LA': _('Laos'),
    'LB': _('Lebanon'),
    'LC': _('St. Lucia'),
    'LI': _('Liechtenstein'),
    'LK': _('Sri Lanka'),
    'LR': _('Liberia'),
    'LS': _('Lesotho'),
    'LT': _('Lithuania'),
    'LU': _('Luxembourg'),
    'LV': _('Latvia'),
    'LY': _('Libya'),
    'MA': _('Morocco'),
    'MC': _('Monaco'),
    'MD': _('Moldova'),
    'ME': _('Montenegro'),
    'MF': _('St. Martin'),
    'MG': _('Madagascar'),
    'MH': _('Marshall Islands'),
    'MK': _('North Macedonia'),
    'ML': _('Mali'),
    'MM': _('Myanmar (Burma)'),
    'MM': _('Myanmar'),
    'MN': _('Mongolia'),
    'MO': _('Macao SAR China'),
    'MO': _('Macao'),
    'MP': _('Northern Mariana Islands'),
    'MQ': _('Martinique'),
    'MR': _('Mauritania'),
    'MS': _('Montserrat'),
    'MT': _('Malta'),
    'MU': _('Mauritius'),
    'MV': _('Maldives'),
    'MW': _('Malawi'),
    'MX': _('Mexico'),
    'MY': _('Malaysia'),
    'MZ': _('Mozambique'),
    'NA': _('Namibia'),
    'NC': _('New Caledonia'),
    'NE': _('Niger'),
    'NF': _('Norfolk Island'),
    'NG': _('Nigeria'),
    'NI': _('Nicaragua'),
    'NL': _('Netherlands'),
    'NO': _('Norway'),
    'NP': _('Nepal'),
    'NR': _('Nauru'),
    'NU': _('Niue'),
    'NZ': _('New Zealand'),
    'NZ': _('Aotearoa New Zealand'),
    'OM': _('Oman'),
    'PA': _('Panama'),
    'PE': _('Peru'),
    'PF': _('French Polynesia'),
    'PG': _('Papua New Guinea'),
    'PH': _('Philippines'),
    'PK': _('Pakistan'),
    'PL': _('Poland'),
    'PM': _('St. Pierre & Miquelon'),
    'PN': _('Pitcairn Islands'),
    'PR': _('Puerto Rico'),
    'PS': _('Palestinian Territories'),
    'PS': _('Palestine'),
    'PT': _('Portugal'),
    'PW': _('Palau'),
    'PY': _('Paraguay'),
    'QA': _('Qatar'),
    'QO': _('Outlying Oceania'),
    'RE': _('Réunion'),
    'RO': _('Romania'),
    'RS': _('Serbia'),
    'RU': _('Russia'),
    'RW': _('Rwanda'),
    'SA': _('Saudi Arabia'),
    'SB': _('Solomon Islands'),
    'SC': _('Seychelles'),
    'SD': _('Sudan'),
    'SE': _('Sweden'),
    'SG': _('Singapore'),
    'SH': _('St. Helena'),
    'SI': _('Slovenia'),
    'SJ': _('Svalbard & Jan Mayen'),
    'SK': _('Slovakia'),
    'SL': _('Sierra Leone'),
    'SM': _('San Marino'),
    'SN': _('Senegal'),
    'SO': _('Somalia'),
    'SR': _('Suriname'),
    'SS': _('South Sudan'),
    'ST': _('São Tomé & Príncipe'),
    'SV': _('El Salvador'),
    'SX': _('Sint Maarten'),
    'SY': _('Syria'),
    'SZ': _('Eswatini'),
    'SZ': _('Swaziland'),
    'TA': _('Tristan da Cunha'),
    'TC': _('Turks & Caicos Islands'),
    'TD': _('Chad'),
    'TF': _('French Southern Territories'),
    'TG': _('Togo'),
    'TH': _('Thailand'),
    'TJ': _('Tajikistan'),
    'TK': _('Tokelau'),
    'TL': _('Timor-Leste'),
    'TL': _('East Timor'),
    'TM': _('Turkmenistan'),
    'TN': _('Tunisia'),
    'TO': _('Tonga'),
    'TR': _('Türkiye'),
    'TR': _('Turkey'),
    'TT': _('Trinidad & Tobago'),
    'TV': _('Tuvalu'),
    'TW': _('Taiwan'),
    'TZ': _('Tanzania'),
    'UA': _('Ukraine'),
    'UG': _('Uganda'),
    'UM': _('U.S. Outlying Islands'),
    'UN': _('United Nations'),
    'UN': _('UN'),
    'US': _('United States'),
    'US': _('US'),
    'UY': _('Uruguay'),
    'UZ': _('Uzbekistan'),
    'VA': _('Vatican City'),
    'VC': _('St. Vincent & Grenadines'),
    'VE': _('Venezuela'),
    'VG': _('British Virgin Islands'),
    'VI': _('U.S. Virgin Islands'),
    'VN': _('Vietnam'),
    'VU': _('Vanuatu'),
    'WF': _('Wallis & Futuna'),
    'WS': _('Samoa'),
    'XA': _('Pseudo-Accents'),
    'XB': _('Pseudo-Bidi'),
    'XK': _('Kosovo'),
    'YE': _('Yemen'),
    'YT': _('Mayotte'),
    'ZA': _('South Africa'),
    'ZM': _('Zambia'),
    'ZW': _('Zimbabwe'),
    'ZZ': _('Unknown Region'),
}
